services:
  go-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: go-api
    environment:
      - APP_ENV=production
      - APP_PORT=8080